spring:
  datasource:
    url: jdbc:mysql://112.94.22.2:3308/test?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
     hibernate:
        ddl-auto: update
     show-sql: true
        
logging:
  level:
    org:
      springframework: INFO
      
management:
  endpoint:
    flowable:
      enabled: true